FROM node
WORKDIR /app
COPY package.json /app
RUN npm install
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
COPY . /app
EXPOSE 3000
CMD /wait &&  npm run test:ci -- --watchAll=false;